lib/orga_app_web/router.ex
defmodule OrgaAppWeb.Router do
  use OrgaAppWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :orga_app

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/", OrgaAppWeb do
    pipe_through [:browser]

    resources "/registration", OrganizationController, singleton: true, only: [:new, :create] 
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
  end

  scope "/", OrgaAppWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", OrgaAppWeb do
  #   pipe_through :api
  # end
end

lib/orga_app/application.ex
defmodule OrgaApp.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      OrgaApp.Repo,
      # Start the endpoint when the application starts
      OrgaAppWeb.Endpoint
      # Starts a worker by calling: OrgaApp.Worker.start_link(arg)
      # {OrgaApp.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: OrgaApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    OrgaAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/orga_app/organizations.ex
defmodule OrgaApp.Organizations do
  @moduledoc """
  The Organizations context.
  """

  import Ecto.Query, warn: false
  alias OrgaApp.Repo

  alias OrgaApp.Organizations.Organization

  @doc """
  Returns the list of organizations.

  ## Examples

      iex> list_organizations()
      [%Organization{}, ...]

  """
  def list_organizations do
    Repo.all(Organization)
  end

  @doc """
  Gets a single organization.

  Raises `Ecto.NoResultsError` if the Organization does not exist.

  ## Examples

      iex> get_organization!(123)
      %Organization{}

      iex> get_organization!(456)
      ** (Ecto.NoResultsError)

  """
  def get_organization!(id), do: Repo.get!(Organization, id)

  @doc """
  Creates a organization.

  ## Examples

      iex> create_organization(%{field: value})
      {:ok, %Organization{}}

      iex> create_organization(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_organization(attrs \\ %{}) do
    %Organization{}
    |> Organization.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a organization.

  ## Examples

      iex> update_organization(organization, %{field: new_value})
      {:ok, %Organization{}}

      iex> update_organization(organization, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_organization(%Organization{} = organization, attrs) do
    organization
    |> Organization.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Organization.

  ## Examples

      iex> delete_organization(organization)
      {:ok, %Organization{}}

      iex> delete_organization(organization)
      {:error, %Ecto.Changeset{}}

  """
  def delete_organization(%Organization{} = organization) do
    Repo.delete(organization)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking organization changes.

  ## Examples

      iex> change_organization(organization)
      %Ecto.Changeset{source: %Organization{}}

  """
  def change_organization(%Organization{} = organization) do
    Organization.changeset(organization, %{})
  end
end

lib/orga_app/organizations/organization.ex
defmodule OrgaApp.Organizations.Organization do
  use Ecto.Schema
  import Ecto.Changeset
  alias OrgaApp.Users.User

  schema "organizations" do
    field :name, :string
    has_many :users, User, on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(organization, attrs) do
    organization
    |> cast(attrs, [:name])
    |> validate_required([:name])
    |> changeset_users
  end

  defp changeset_users(changeset) do
    case Ecto.get_meta(changeset.data, :state) do
      :built -> cast_assoc(changeset, :users, required: true)
      _any -> changeset
    end
  end
end

lib/orga_app/repo.ex
defmodule OrgaApp.Repo do
  use Ecto.Repo,
    otp_app: :orga_app,
    adapter: Ecto.Adapters.Postgres
end

lib/orga_app/users/user.ex
defmodule OrgaApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  use Pow.Extension.Ecto.Schema,
    extensions: [PowResetPassword, PowEmailConfirmation, PowInvitation]

  alias OrgaApp.Organizations.Organization

  schema "users" do
    belongs_to :organization, Organization

    pow_user_fields()

    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
    |> Ecto.Changeset.assoc_constraint(:organization)
  end

   def invite_changeset(user_or_changeset, invited_by, attrs) do
    user_or_changeset
    |> pow_invite_changeset(invited_by, attrs)
    |> changeset_organization(invited_by)
  end

  defp changeset_organization(changeset, invited_by) do
    Ecto.Changeset.change(changeset, organization_id: invited_by.organization_id)
  end
end

lib/orga_app_web/controllers/organization_controller.ex
defmodule OrgaAppWeb.OrganizationController do
  use OrgaAppWeb, :controller

  alias OrgaApp.{Organizations.Organization, Repo}

  def new(conn, _params) do
    changeset = Organization.changeset(%Organization{}, %{})

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"organization" => user_params}) do
    %Organization{}
    |> Organization.changeset(user_params)
    |> Repo.insert()
    |> case do
      {:ok, organization} ->
        conn
        |> auth_user(organization.users)
        |> put_flash(:info, "Welcome!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end  

  defp auth_user(conn, [user]) do
    config = Pow.Plug.fetch_config(conn)

    Pow.Plug.get_plug(config).do_create(conn, user, config)
  end
end

lib/orga_app_web/controllers/page_controller.ex
defmodule OrgaAppWeb.PageController do
  use OrgaAppWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/orga_app_web/controllers/registration_controller.ex
defmodule OrgaAppWeb.RegistrationController do
  use OrgaAppWeb, :controller

  alias OrgaApp.{Organizations.Organization, Repo}

  def new(conn, _params) do
    changeset = Organization.changeset(%Organization{}, %{})

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"organization" => user_params}) do
    %Organization{}
    |> Organization.changeset(user_params)
    |> Repo.insert()
    |> case do
      {:ok, organization} ->
        conn
        |> auth_user(organization.users)
        |> put_flash(:info, "Welcome!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end  

  defp auth_user(conn, [user]) do
    config = Pow.Plug.fetch_config(conn)

    Pow.Plug.get_plug(config).do_create(conn, user, config)
  end
end

lib/orga_app_web/views/error_view.ex
defmodule OrgaAppWeb.ErrorView do
  use OrgaAppWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/orga_app_web/views/layout_view.ex
defmodule OrgaAppWeb.LayoutView do
  use OrgaAppWeb, :view
end

lib/orga_app_web/views/organization_view.ex
defmodule OrgaAppWeb.OrganizationView do
  use OrgaAppWeb, :view
end

lib/orga_app_web/views/page_view.ex
defmodule OrgaAppWeb.PageView do
  use OrgaAppWeb, :view
end

lib/orga_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>OrgaApp · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <li><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/orga_app_web/templates/organization/new.html.eex
<%= form_for @changeset, Routes.organization_path(@conn, :create), fn f -> %>
  <%= text_input f, :name %>

  <%= inputs_for f, :users, [append: [%OrgaApp.Users.User{}]], fn f_user -> %>
    <%= label f_user, :email, "email" %>
    <%= email_input f_user, :email %>
    <%= error_tag f_user, :email %>

    <%= label f_user, :password, "password" %>
    <%= password_input f_user, :password %>
    <%= error_tag f_user, :password %>

    <%= label f_user, :confirm_password, "confirm_password" %>
    <%= password_input f_user, :confirm_password %>
    <%= error_tag f_user, :confirm_password %>
  <% end %>
  <%= submit "Submit" %>
<% end %>

lib/orga_app_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>